import lmx


def test_lmx_lazy_exports_resolve_expected_symbols():
    assert callable(lmx.generate_rect_duct_mesh)
    assert callable(lmx.generate_bent_pipe_mesh)
    assert callable(lmx.enable_compilation_cache)
    assert callable(lmx.load_fringing_pipe_profile)
    assert callable(lmx.load_shercliff_analytical)
    assert callable(lmx.load_hunt_analytical)
    assert callable(lmx.build_hartmann_autodiff_problem)
    assert callable(lmx.build_extruded_response_targets)
    assert callable(lmx.hartmann_mean_velocity_gradients)
    assert callable(lmx.hartmann_profile_loss_gradients)
    assert callable(lmx.run_hartmann_profile_inverse_design)
    assert callable(lmx.build_square_duct_fringing_benchmark)
    assert callable(lmx.build_layered_duct_extruded_problem)
    assert callable(lmx.build_bent_pipe_extruded_problem)
    assert callable(lmx.build_variable_field_duct_extruded_problem)
    assert callable(lmx.build_variable_field_layered_extruded_problem)
    assert callable(lmx.build_variable_field_pipe_ogrid_extruded_problem)
    assert callable(lmx.build_variable_field_bent_pipe_extruded_problem)
    assert callable(lmx.build_magnetic_obstacle_rect_extruded_problem)
    assert callable(lmx.build_wham_mirror_pipe_extruded_problem)
    assert callable(lmx.build_pipe_ogrid_extruded_problem)
    assert callable(lmx.run_extruded_inductionless_slice)
    assert callable(lmx.solve_extruded_inductionless)
    assert callable(lmx.validate_bent_pipe_low_de_baseline)
    assert callable(lmx.validate_variable_field_extruded_solution)
    assert callable(lmx.validate_variable_field_pipe_solution)
    assert callable(lmx.validate_magnetic_obstacle_baseline)
    assert callable(lmx.validate_magnetic_obstacle_benchmark)
    assert callable(lmx.validate_magnetic_obstacle_literature_slice)
    assert callable(lmx.validate_wham_mirror_pipe_baseline)
    assert callable(lmx.build_square_duct_extruded_problem)
    assert callable(lmx.build_fringing_autodiff_problem)
    assert callable(lmx.wham_mirror_pressure_drop_history)
    assert callable(lmx.wham_mirror_pressure_drop_sensitivity)
    assert callable(lmx.extruded_rect_response_history)
    assert callable(lmx.extruded_rect_projection_iteration_history)
    assert callable(lmx.extruded_rect_projection_field_loss_gradients)
    assert callable(lmx.extruded_rect_projection_trajectory_loss_gradients)
    assert callable(lmx.fringing_mean_velocity_history)
    assert callable(lmx.fringing_response_history)
    assert callable(lmx.extruded_rect_response_loss_gradients)
    assert callable(lmx.run_fringing_history_inverse_design)
    assert callable(lmx.run_fringing_response_inverse_design)
    assert callable(lmx.run_extruded_rect_inverse_design)
    assert callable(lmx.run_extruded_rect_projection_field_inverse_design)
    assert callable(lmx.run_extruded_rect_projection_trajectory_inverse_design)
    assert callable(lmx.run_extruded_target_inverse_design)
    assert callable(lmx.benchmark_sharded_stencil)
    assert callable(lmx.write_scaling_report)
    assert callable(lmx.solve_case_snapshots)
    assert callable(lmx.write_case_overview_plots)
    assert callable(lmx.write_extruded_overview_plots)
    assert callable(lmx.write_magnetic_obstacle_benchmark_plots)
    assert callable(lmx.write_magnetic_obstacle_regime_plots)
    assert callable(lmx.write_bent_pipe_overview_plots)
    assert callable(lmx.write_geometry_gallery_plots)
    assert callable(lmx.write_geometry_preview_plots)
    assert callable(lmx.write_cross_section_field_plots)
    assert callable(lmx.write_wham_mirror_overview_plots)
    assert callable(lmx.write_transient_movies)
    assert callable(lmx.write_strong_scaling_plots)
    assert callable(lmx.write_autodiff_plots)
    assert callable(lmx.solve_closed_channel_benchmark)
    assert callable(lmx.write_lm_duct_geometry_setup_figure)
    assert callable(lmx.write_structured_mesh_figure)
    assert callable(lmx.write_boundary_layer_figure)
    assert callable(lmx.write_annotated_layer_figure)
    assert callable(lmx.write_velocity_profile_volume_figure)
    assert callable(lmx.write_closed_channel_profile_comparison_figure)
    assert callable(lmx.write_closed_channel_startup_movies)
    assert callable(lmx.make_divergence_free_cross_section_field)
    assert callable(lmx.make_localized_divergence_free_obstacle_field)
    assert callable(lmx.cross_section_divergence_metrics)
    assert callable(lmx.load_tabulated_field)
    assert callable(lmx.sample_tabulated_cross_section_field)
    assert callable(lmx.sample_tabulated_field_volume)
    assert callable(lmx.sample_wham_mirror_field)
    assert callable(lmx.sample_wham_mirror_axis_profile)
    assert callable(lmx.wham_mirror_station_scale)
    assert callable(lmx.write_tabulated_field_npz)
    assert callable(lmx.write_wham_mirror_field_npz)
    assert callable(lmx.build_q2d_decay_case)
    assert callable(lmx.build_q2d_forced_case)
    assert callable(lmx.build_q2d_wall_bounded_forced_case)
    assert callable(lmx.solve_q2d_decay)
    assert callable(lmx.solve_q2d_forced)
    assert callable(lmx.solve_q2d_wall_bounded_forced)
    assert callable(lmx.validate_q2d_decay_solution)
    assert callable(lmx.validate_q2d_forced_solution)
    assert callable(lmx.validate_q2d_wall_bounded_forced_solution)
    assert callable(lmx.write_q2d_decay_plots)
    assert callable(lmx.write_q2d_forced_plots)
    assert callable(lmx.write_q2d_wall_bounded_forced_plots)
    assert "solve_steady" in lmx.__all__
    assert "build_hartmann_autodiff_problem" in lmx.__all__
    assert "write_case_overview_plots" in lmx.__all__


def test_lmx_lazy_exports_reject_unknown_name():
    try:
        getattr(lmx, "definitely_missing_symbol")
    except AttributeError as exc:
        assert str(exc) == "definitely_missing_symbol"
    else:
        raise AssertionError("Expected AttributeError for missing lazy export.")
