"""LMX public API with lazy imports for lightweight startup."""

from __future__ import annotations

from importlib import import_module


__all__ = [
    "benchmark_solver",
    "compare_with_reference_outputs",
    "compare_magnetic_obstacle_reference_observables",
    "compare_scalar_reference_observables",
    "external_validation_readiness_rows",
    "generate_layered_duct_mesh",
    "generate_layered_duct_mesh_from_fluid_faces",
    "generate_bent_pipe_mesh",
    "generate_pipe_ogrid_mesh",
    "generate_rect_duct_mesh",
    "generate_rect_duct_mesh_from_faces",
    "enable_compilation_cache",
    "load_closed_channel_analytical",
    "load_hunt_analytical",
    "load_shercliff_analytical",
    "load_fringing_pipe_profile",
    "load_processed_slice",
    "processed_slice_area_mean",
    "processed_slice_field_grid",
    "processed_slice_point_mesh",
    "make_hartmann_case",
    "make_hunt_case",
    "make_shercliff_case",
    "run_case_example",
    "run_theory_meeting_demo",
    "solve_steady",
    "solve_transient",
    "build_hartmann_autodiff_problem",
    "build_fringing_autodiff_problem",
    "extruded_rect_response_history",
    "extruded_rect_projection_history",
    "extruded_rect_projection_iteration_history",
    "extruded_rect_projection_field_loss_gradients",
    "extruded_rect_projection_trajectory_loss_gradients",
    "fringing_response_history",
    "wham_mirror_pressure_drop_history",
    "wham_mirror_pressure_drop_sensitivity",
    "build_extruded_response_targets",
    "hartmann_mean_velocity_gradients",
    "hartmann_mean_velocity_finite_difference_gradients",
    "hartmann_profile_loss_gradients",
    "fringing_mean_velocity_history",
    "fringing_history_loss_gradients",
    "fringing_response_loss_gradients",
    "extruded_rect_response_loss_gradients",
    "extruded_rect_projection_loss_gradients",
    "run_fringing_history_inverse_design",
    "run_fringing_response_inverse_design",
    "run_extruded_rect_inverse_design",
    "run_extruded_rect_projection_inverse_design",
    "run_extruded_rect_projection_field_inverse_design",
    "run_extruded_rect_projection_trajectory_inverse_design",
    "run_extruded_target_inverse_design",
    "run_hartmann_profile_inverse_design",
    "solve_differentiable_hartmann",
    "benchmark_sharded_stencil",
    "summarize_strong_scaling_records",
    "write_benchmark_report",
    "write_scaling_report",
    "write_strong_scaling_summary_table",
    "solve_case_snapshots",
    "write_case_overview_plots",
    "write_extruded_overview_plots",
    "write_magnetic_obstacle_benchmark_plots",
    "write_magnetic_obstacle_schematic_plots",
    "write_magnetic_obstacle_regime_plots",
    "write_bent_pipe_overview_plots",
    "write_geometry_gallery_plots",
    "write_geometry_preview_plots",
    "write_cross_section_field_plots",
    "write_tabulated_field_reconstruction_plots",
    "write_wham_mirror_overview_plots",
    "write_transient_movies",
    "write_strong_scaling_plots",
    "write_autodiff_plots",
    "write_operator_verification_plots",
    "write_interface_verification_plots",
    "write_freemhd_observable_parity_plots",
    "summarize_observable_ladder_levels",
    "write_observable_ladder_table",
    "solve_closed_channel_benchmark",
    "write_lm_duct_geometry_setup_figure",
    "write_structured_mesh_figure",
    "write_boundary_layer_figure",
    "write_annotated_layer_figure",
    "write_velocity_profile_volume_figure",
    "write_closed_channel_profile_comparison_figure",
    "write_hartmann_validation_ladder_figure",
    "write_closed_channel_startup_movies",
    "build_square_duct_fringing_benchmark",
    "build_square_duct_extruded_problem",
    "build_layered_duct_extruded_problem",
    "build_bent_pipe_extruded_problem",
    "build_variable_field_duct_extruded_problem",
    "build_variable_field_layered_extruded_problem",
    "build_variable_field_pipe_ogrid_extruded_problem",
    "build_variable_field_bent_pipe_extruded_problem",
    "build_magnetic_obstacle_rect_extruded_problem",
    "build_wham_mirror_pipe_extruded_problem",
    "build_pipe_ogrid_extruded_problem",
    "run_extruded_inductionless_slice",
    "run_fringing_station_sweep",
    "solve_extruded_inductionless",
    "validate_extruded_inductionless_solution",
    "validate_bent_pipe_low_de_baseline",
    "validate_variable_field_extruded_solution",
    "validate_variable_field_pipe_solution",
    "validate_magnetic_obstacle_baseline",
    "validate_magnetic_obstacle_benchmark",
    "validate_magnetic_obstacle_literature_slice",
    "validate_wham_mirror_pipe_baseline",
    "make_divergence_free_cross_section_field",
    "make_localized_divergence_free_obstacle_field",
    "sample_cross_section_field",
    "cross_section_divergence_metrics",
    "save_cross_section_divergence_report",
    "load_tabulated_field",
    "tabulated_field_quality_metrics",
    "tabulated_cross_section_reconstruction_metrics",
    "sample_tabulated_cross_section_field",
    "sample_tabulated_field_volume",
    "sample_wham_mirror_field",
    "sample_wham_mirror_axis_profile",
    "wham_mirror_station_scale",
    "write_tabulated_field_npz",
    "write_wham_mirror_field_npz",
    "build_q2d_decay_case",
    "build_q2d_forced_case",
    "build_q2d_wall_bounded_forced_case",
    "build_q2d_turbulence_decay_case",
    "solve_q2d_decay",
    "solve_q2d_forced",
    "solve_q2d_wall_bounded_forced",
    "solve_q2d_turbulence_decay",
    "validate_q2d_decay_solution",
    "validate_q2d_decay_energy_budget",
    "validate_q2d_forced_solution",
    "validate_q2d_forced_energy_budget",
    "validate_q2d_wall_bounded_forced_solution",
    "validate_q2d_wall_bounded_energy_budget",
    "validate_q2d_turbulence_decay_observables",
    "q2d_modal_energy_budget",
    "q2d_energy_spectrum",
    "q2d_turbulence_observables",
    "q2d_turbulence_readiness_metrics",
    "write_q2d_decay_plots",
    "write_q2d_forced_plots",
    "write_q2d_wall_bounded_forced_plots",
    "write_q2d_turbulence_observable_plots",
    "write_q2d_turbulence_decay_movie",
    "load_magnetic_obstacle_reference_observables",
    "load_scalar_reference_observables",
    "q2d_turbulence_reference_template_rows",
    "dean_vortex_reference_template_rows",
    "magnetic_obstacle_reference_template_rows",
    "write_dean_vortex_reference_template",
    "summarize_external_validation_readiness",
    "write_external_validation_readiness_panel",
    "write_magnetic_obstacle_reference_comparison_plots",
    "write_magnetic_obstacle_reference_comparison_table",
    "write_magnetic_obstacle_reference_template",
    "write_q2d_turbulence_reference_template",
    "write_scalar_reference_comparison_plots",
    "write_scalar_reference_comparison_table",
    "write_scalar_reference_template",
]


_EXPORTS = {
    "benchmark_solver": ("lmx.benchmarks", "benchmark_solver"),
    "write_benchmark_report": ("lmx.benchmarks", "write_benchmark_report"),
    "make_hartmann_case": ("lmx.cases", "make_hartmann_case"),
    "make_hunt_case": ("lmx.cases", "make_hunt_case"),
    "make_shercliff_case": ("lmx.cases", "make_shercliff_case"),
    "run_case_example": ("lmx.example_runner", "run_case_example"),
    "run_theory_meeting_demo": ("lmx.example_runner", "run_theory_meeting_demo"),
    "solve_case_snapshots": ("lmx.example_runner", "solve_case_snapshots"),
    "generate_layered_duct_mesh": ("lmx.mesh", "generate_layered_duct_mesh"),
    "generate_layered_duct_mesh_from_fluid_faces": ("lmx.mesh", "generate_layered_duct_mesh_from_fluid_faces"),
    "generate_bent_pipe_mesh": ("lmx.mesh", "generate_bent_pipe_mesh"),
    "generate_pipe_ogrid_mesh": ("lmx.mesh", "generate_pipe_ogrid_mesh"),
    "generate_rect_duct_mesh": ("lmx.mesh", "generate_rect_duct_mesh"),
    "generate_rect_duct_mesh_from_faces": ("lmx.mesh", "generate_rect_duct_mesh_from_faces"),
    "enable_compilation_cache": ("lmx.jax_setup", "enable_compilation_cache"),
    "load_closed_channel_analytical": ("lmx.reference_data", "load_closed_channel_analytical"),
    "load_hunt_analytical": ("lmx.reference_data", "load_hunt_analytical"),
    "load_shercliff_analytical": ("lmx.reference_data", "load_shercliff_analytical"),
    "load_fringing_pipe_profile": ("lmx.reference_data", "load_fringing_pipe_profile"),
    "load_processed_slice": ("lmx.reference_data", "load_processed_slice"),
    "processed_slice_area_mean": ("lmx.reference_data", "processed_slice_area_mean"),
    "processed_slice_field_grid": ("lmx.reference_data", "processed_slice_field_grid"),
    "processed_slice_point_mesh": ("lmx.reference_data", "processed_slice_point_mesh"),
    "solve_steady": ("lmx.solvers", "solve_steady"),
    "solve_transient": ("lmx.solvers", "solve_transient"),
    "compare_with_reference_outputs": ("lmx.validation", "compare_with_reference_outputs"),
    "compare_magnetic_obstacle_reference_observables": (
        "lmx.external_validation",
        "compare_magnetic_obstacle_reference_observables",
    ),
    "compare_scalar_reference_observables": (
        "lmx.external_validation",
        "compare_scalar_reference_observables",
    ),
    "external_validation_readiness_rows": (
        "lmx.external_validation",
        "external_validation_readiness_rows",
    ),
    "load_scalar_reference_observables": (
        "lmx.external_validation",
        "load_scalar_reference_observables",
    ),
    "load_magnetic_obstacle_reference_observables": (
        "lmx.external_validation",
        "load_magnetic_obstacle_reference_observables",
    ),
    "q2d_turbulence_reference_template_rows": (
        "lmx.external_validation",
        "q2d_turbulence_reference_template_rows",
    ),
    "dean_vortex_reference_template_rows": (
        "lmx.external_validation",
        "dean_vortex_reference_template_rows",
    ),
    "magnetic_obstacle_reference_template_rows": (
        "lmx.external_validation",
        "magnetic_obstacle_reference_template_rows",
    ),
    "write_dean_vortex_reference_template": (
        "lmx.external_validation",
        "write_dean_vortex_reference_template",
    ),
    "summarize_external_validation_readiness": (
        "lmx.external_validation",
        "summarize_external_validation_readiness",
    ),
    "write_external_validation_readiness_panel": (
        "lmx.external_validation",
        "write_external_validation_readiness_panel",
    ),
    "write_magnetic_obstacle_reference_comparison_table": (
        "lmx.external_validation",
        "write_magnetic_obstacle_reference_comparison_table",
    ),
    "write_magnetic_obstacle_reference_comparison_plots": (
        "lmx.external_validation",
        "write_magnetic_obstacle_reference_comparison_plots",
    ),
    "write_magnetic_obstacle_reference_template": (
        "lmx.external_validation",
        "write_magnetic_obstacle_reference_template",
    ),
    "write_q2d_turbulence_reference_template": (
        "lmx.external_validation",
        "write_q2d_turbulence_reference_template",
    ),
    "write_scalar_reference_comparison_table": (
        "lmx.external_validation",
        "write_scalar_reference_comparison_table",
    ),
    "write_scalar_reference_comparison_plots": (
        "lmx.external_validation",
        "write_scalar_reference_comparison_plots",
    ),
    "write_scalar_reference_template": (
        "lmx.external_validation",
        "write_scalar_reference_template",
    ),
    "build_hartmann_autodiff_problem": ("lmx.autodiff", "build_hartmann_autodiff_problem"),
    "build_fringing_autodiff_problem": ("lmx.autodiff", "build_fringing_autodiff_problem"),
    "extruded_rect_response_history": ("lmx.autodiff", "extruded_rect_response_history"),
    "extruded_rect_projection_history": ("lmx.autodiff", "extruded_rect_projection_history"),
    "extruded_rect_projection_iteration_history": ("lmx.autodiff", "extruded_rect_projection_iteration_history"),
    "extruded_rect_projection_field_loss_gradients": ("lmx.autodiff", "extruded_rect_projection_field_loss_gradients"),
    "extruded_rect_projection_trajectory_loss_gradients": ("lmx.autodiff", "extruded_rect_projection_trajectory_loss_gradients"),
    "fringing_response_history": ("lmx.autodiff", "fringing_response_history"),
    "wham_mirror_pressure_drop_history": ("lmx.autodiff", "wham_mirror_pressure_drop_history"),
    "wham_mirror_pressure_drop_sensitivity": ("lmx.autodiff", "wham_mirror_pressure_drop_sensitivity"),
    "build_extruded_response_targets": ("lmx.autodiff", "build_extruded_response_targets"),
    "hartmann_mean_velocity_gradients": ("lmx.autodiff", "hartmann_mean_velocity_gradients"),
    "hartmann_mean_velocity_finite_difference_gradients": ("lmx.autodiff", "hartmann_mean_velocity_finite_difference_gradients"),
    "hartmann_profile_loss_gradients": ("lmx.autodiff", "hartmann_profile_loss_gradients"),
    "fringing_mean_velocity_history": ("lmx.autodiff", "fringing_mean_velocity_history"),
    "fringing_history_loss_gradients": ("lmx.autodiff", "fringing_history_loss_gradients"),
    "fringing_response_loss_gradients": ("lmx.autodiff", "fringing_response_loss_gradients"),
    "extruded_rect_response_loss_gradients": ("lmx.autodiff", "extruded_rect_response_loss_gradients"),
    "extruded_rect_projection_loss_gradients": ("lmx.autodiff", "extruded_rect_projection_loss_gradients"),
    "run_fringing_history_inverse_design": ("lmx.autodiff", "run_fringing_history_inverse_design"),
    "run_fringing_response_inverse_design": ("lmx.autodiff", "run_fringing_response_inverse_design"),
    "run_extruded_rect_inverse_design": ("lmx.autodiff", "run_extruded_rect_inverse_design"),
    "run_extruded_rect_projection_inverse_design": ("lmx.autodiff", "run_extruded_rect_projection_inverse_design"),
    "run_extruded_rect_projection_field_inverse_design": ("lmx.autodiff", "run_extruded_rect_projection_field_inverse_design"),
    "run_extruded_rect_projection_trajectory_inverse_design": ("lmx.autodiff", "run_extruded_rect_projection_trajectory_inverse_design"),
    "run_extruded_target_inverse_design": ("lmx.autodiff", "run_extruded_target_inverse_design"),
    "run_hartmann_profile_inverse_design": ("lmx.autodiff", "run_hartmann_profile_inverse_design"),
    "solve_differentiable_hartmann": ("lmx.autodiff", "solve_differentiable_hartmann"),
    "benchmark_sharded_stencil": ("lmx.scaling", "benchmark_sharded_stencil"),
    "summarize_strong_scaling_records": ("lmx.scaling", "summarize_strong_scaling_records"),
    "write_scaling_report": ("lmx.scaling", "write_scaling_report"),
    "write_strong_scaling_summary_table": ("lmx.scaling", "write_strong_scaling_summary_table"),
    "write_case_overview_plots": ("lmx.plotting", "write_case_overview_plots"),
    "write_extruded_overview_plots": ("lmx.plotting", "write_extruded_overview_plots"),
    "write_magnetic_obstacle_benchmark_plots": ("lmx.plotting", "write_magnetic_obstacle_benchmark_plots"),
    "write_magnetic_obstacle_schematic_plots": ("lmx.plotting", "write_magnetic_obstacle_schematic_plots"),
    "write_magnetic_obstacle_regime_plots": ("lmx.plotting", "write_magnetic_obstacle_regime_plots"),
    "write_bent_pipe_overview_plots": ("lmx.plotting", "write_bent_pipe_overview_plots"),
    "write_geometry_gallery_plots": ("lmx.plotting", "write_geometry_gallery_plots"),
    "write_geometry_preview_plots": ("lmx.plotting", "write_geometry_preview_plots"),
    "write_cross_section_field_plots": ("lmx.plotting", "write_cross_section_field_plots"),
    "write_tabulated_field_reconstruction_plots": (
        "lmx.plotting",
        "write_tabulated_field_reconstruction_plots",
    ),
    "write_wham_mirror_overview_plots": ("lmx.plotting", "write_wham_mirror_overview_plots"),
    "write_transient_movies": ("lmx.plotting", "write_transient_movies"),
    "write_strong_scaling_plots": ("lmx.plotting", "write_strong_scaling_plots"),
    "write_autodiff_plots": ("lmx.plotting", "write_autodiff_plots"),
    "write_operator_verification_plots": ("lmx.plotting", "write_operator_verification_plots"),
    "write_interface_verification_plots": ("lmx.plotting", "write_interface_verification_plots"),
    "write_freemhd_parity_plots": ("lmx.plotting", "write_freemhd_parity_plots"),
    "write_freemhd_observable_parity_plots": ("lmx.plotting", "write_freemhd_observable_parity_plots"),
    "summarize_observable_ladder_levels": ("lmx.freemhd", "summarize_observable_ladder_levels"),
    "write_observable_ladder_table": ("lmx.freemhd", "write_observable_ladder_table"),
    "solve_closed_channel_benchmark": ("lmx.showcase", "solve_closed_channel_benchmark"),
    "write_lm_duct_geometry_setup_figure": ("lmx.showcase", "write_lm_duct_geometry_setup_figure"),
    "write_structured_mesh_figure": ("lmx.showcase", "write_structured_mesh_figure"),
    "write_boundary_layer_figure": ("lmx.showcase", "write_boundary_layer_figure"),
    "write_annotated_layer_figure": ("lmx.showcase", "write_annotated_layer_figure"),
    "write_velocity_profile_volume_figure": ("lmx.showcase", "write_velocity_profile_volume_figure"),
    "write_closed_channel_profile_comparison_figure": ("lmx.showcase", "write_closed_channel_profile_comparison_figure"),
    "write_hartmann_validation_ladder_figure": ("lmx.showcase", "write_hartmann_validation_ladder_figure"),
    "write_closed_channel_startup_movies": ("lmx.showcase", "write_closed_channel_startup_movies"),
    "build_square_duct_fringing_benchmark": ("lmx.fringing", "build_square_duct_fringing_benchmark"),
    "build_square_duct_extruded_problem": ("lmx.fringing", "build_square_duct_extruded_problem"),
    "build_layered_duct_extruded_problem": ("lmx.fringing", "build_layered_duct_extruded_problem"),
    "build_bent_pipe_extruded_problem": ("lmx.fringing", "build_bent_pipe_extruded_problem"),
    "build_variable_field_duct_extruded_problem": ("lmx.fringing", "build_variable_field_duct_extruded_problem"),
    "build_variable_field_layered_extruded_problem": ("lmx.fringing", "build_variable_field_layered_extruded_problem"),
    "build_variable_field_pipe_ogrid_extruded_problem": ("lmx.fringing", "build_variable_field_pipe_ogrid_extruded_problem"),
    "build_variable_field_bent_pipe_extruded_problem": ("lmx.fringing", "build_variable_field_bent_pipe_extruded_problem"),
    "build_magnetic_obstacle_rect_extruded_problem": ("lmx.fringing", "build_magnetic_obstacle_rect_extruded_problem"),
    "build_wham_mirror_pipe_extruded_problem": ("lmx.fringing", "build_wham_mirror_pipe_extruded_problem"),
    "build_pipe_ogrid_extruded_problem": ("lmx.fringing", "build_pipe_ogrid_extruded_problem"),
    "run_extruded_inductionless_slice": ("lmx.fringing", "run_extruded_inductionless_slice"),
    "run_fringing_station_sweep": ("lmx.fringing", "run_fringing_station_sweep"),
    "solve_extruded_inductionless": ("lmx.fringing", "solve_extruded_inductionless"),
    "validate_extruded_inductionless_solution": ("lmx.fringing", "validate_extruded_inductionless_solution"),
    "validate_bent_pipe_low_de_baseline": ("lmx.fringing", "validate_bent_pipe_low_de_baseline"),
    "validate_variable_field_extruded_solution": ("lmx.fringing", "validate_variable_field_extruded_solution"),
    "validate_variable_field_pipe_solution": ("lmx.fringing", "validate_variable_field_pipe_solution"),
    "validate_magnetic_obstacle_baseline": ("lmx.fringing", "validate_magnetic_obstacle_baseline"),
    "validate_magnetic_obstacle_benchmark": ("lmx.fringing", "validate_magnetic_obstacle_benchmark"),
    "validate_magnetic_obstacle_literature_slice": ("lmx.fringing", "validate_magnetic_obstacle_literature_slice"),
    "magnetic_obstacle_literature_reference_cases": ("lmx.fringing", "magnetic_obstacle_literature_reference_cases"),
    "validate_magnetic_obstacle_external_readiness": ("lmx.fringing", "validate_magnetic_obstacle_external_readiness"),
    "validate_wham_mirror_pipe_baseline": ("lmx.fringing", "validate_wham_mirror_pipe_baseline"),
    "make_divergence_free_cross_section_field": ("lmx.field_models", "make_divergence_free_cross_section_field"),
    "make_localized_divergence_free_obstacle_field": ("lmx.field_models", "make_localized_divergence_free_obstacle_field"),
    "sample_cross_section_field": ("lmx.field_models", "sample_cross_section_field"),
    "cross_section_divergence_metrics": ("lmx.field_models", "cross_section_divergence_metrics"),
    "save_cross_section_divergence_report": ("lmx.field_models", "save_cross_section_divergence_report"),
    "load_tabulated_field": ("lmx.field_models", "load_tabulated_field"),
    "tabulated_field_quality_metrics": ("lmx.field_models", "tabulated_field_quality_metrics"),
    "tabulated_cross_section_reconstruction_metrics": (
        "lmx.field_models",
        "tabulated_cross_section_reconstruction_metrics",
    ),
    "sample_tabulated_cross_section_field": ("lmx.field_models", "sample_tabulated_cross_section_field"),
    "sample_tabulated_field_volume": ("lmx.field_models", "sample_tabulated_field_volume"),
    "sample_wham_mirror_field": ("lmx.field_models", "sample_wham_mirror_field"),
    "sample_wham_mirror_axis_profile": ("lmx.field_models", "sample_wham_mirror_axis_profile"),
    "wham_mirror_station_scale": ("lmx.field_models", "wham_mirror_station_scale"),
    "write_tabulated_field_npz": ("lmx.field_models", "write_tabulated_field_npz"),
    "write_wham_mirror_field_npz": ("lmx.field_models", "write_wham_mirror_field_npz"),
    "build_q2d_decay_case": ("lmx.q2d", "build_q2d_decay_case"),
    "build_q2d_forced_case": ("lmx.q2d", "build_q2d_forced_case"),
    "build_q2d_wall_bounded_forced_case": ("lmx.q2d", "build_q2d_wall_bounded_forced_case"),
    "build_q2d_turbulence_decay_case": ("lmx.q2d", "build_q2d_turbulence_decay_case"),
    "solve_q2d_decay": ("lmx.q2d", "solve_q2d_decay"),
    "solve_q2d_forced": ("lmx.q2d", "solve_q2d_forced"),
    "solve_q2d_wall_bounded_forced": ("lmx.q2d", "solve_q2d_wall_bounded_forced"),
    "solve_q2d_turbulence_decay": ("lmx.q2d", "solve_q2d_turbulence_decay"),
    "validate_q2d_decay_solution": ("lmx.q2d", "validate_q2d_decay_solution"),
    "validate_q2d_decay_energy_budget": ("lmx.q2d", "validate_q2d_decay_energy_budget"),
    "validate_q2d_forced_solution": ("lmx.q2d", "validate_q2d_forced_solution"),
    "validate_q2d_forced_energy_budget": ("lmx.q2d", "validate_q2d_forced_energy_budget"),
    "validate_q2d_wall_bounded_forced_solution": ("lmx.q2d", "validate_q2d_wall_bounded_forced_solution"),
    "validate_q2d_wall_bounded_energy_budget": ("lmx.q2d", "validate_q2d_wall_bounded_energy_budget"),
    "validate_q2d_turbulence_decay_observables": ("lmx.q2d", "validate_q2d_turbulence_decay_observables"),
    "q2d_modal_energy_budget": ("lmx.q2d", "q2d_modal_energy_budget"),
    "q2d_energy_spectrum": ("lmx.q2d", "q2d_energy_spectrum"),
    "q2d_turbulence_observables": ("lmx.q2d", "q2d_turbulence_observables"),
    "q2d_turbulence_readiness_metrics": ("lmx.q2d", "q2d_turbulence_readiness_metrics"),
    "write_q2d_decay_plots": ("lmx.q2d", "write_q2d_decay_plots"),
    "write_q2d_forced_plots": ("lmx.q2d", "write_q2d_forced_plots"),
    "write_q2d_wall_bounded_forced_plots": ("lmx.q2d", "write_q2d_wall_bounded_forced_plots"),
    "write_q2d_turbulence_observable_plots": ("lmx.q2d", "write_q2d_turbulence_observable_plots"),
    "write_q2d_turbulence_decay_movie": ("lmx.q2d", "write_q2d_turbulence_decay_movie"),
}


def __getattr__(name: str):
    if name not in _EXPORTS:
        raise AttributeError(name)
    module_name, attr_name = _EXPORTS[name]
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
