name: docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-lmx
        with:
          extras: docs,dev

      - name: Verify provenance
        run: python scripts/manage_provenance.py --check

      - name: Build documentation
        run: python -m sphinx -W -b html docs docs/_build/html
